-- Rollback for 0017_streams_drop_room_name.sql
--
-- There is no rollback runner in this branch yet: RunMigrations reads only the
-- top level of migrations/ and skips subdirectories, so nothing will execute this
-- file on its own. It exists so the rollback is written down and reviewable
-- alongside the migration it reverses, and so a rollback runner has a
-- convention to follow (migrations/down/<name>.down.sql, applied manually for
-- now). See docs/CODE_REVIEW.md if a runner gets added.
--
-- Restores the column as a plain nullable TEXT.
--
-- NOT NULL is deliberately not restored. This file has to work against a
-- database that has rows, and every existing row would have to be backfilled
-- with a value nobody chose. Inventing placeholder room names would write false
-- data into the table that then has to be distinguished from real values later.
-- NULL is the honest representation of "this row never had one".
--
-- UNIQUE is not restored either. Postgres permits any number of NULLs in a
-- unique index, so re-adding it would not have blocked the NULLs, but it would
-- also do nothing useful here: the column is vestigial and re-imposing a
-- constraint on it constrains a future implementer to invent values for every
-- row. If a future media layer needs a non-null unique identifier, that belongs
-- in the migration that introduces it.
--
-- Databases that applied this migration under its previous name
-- (0015_streams_drop_livekit_room_name.sql) should have their schema_migrations
-- row UPDATEd to the new filename rather than left stale. RunMigrations builds
-- its work list from the files on disk and never walks schema_migrations looking
-- for rows it cannot match, so a row naming a file that no longer exists is
-- silently ignored: no error, no warning, and the renamed migration is then
-- treated as unapplied and runs again.

ALTER TABLE streams ADD COLUMN IF NOT EXISTS livekit_room_name TEXT;